/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { imagesCreateSignedUrl } from "../funcs/imagesCreateSignedUrl.js";
import { imagesDeleteImage } from "../funcs/imagesDeleteImage.js";
import { imagesDeleteImagePath } from "../funcs/imagesDeleteImagePath.js";
import { imagesGetImage } from "../funcs/imagesGetImage.js";
import { imagesListImages } from "../funcs/imagesListImages.js";
import { imagesSearchImages } from "../funcs/imagesSearchImages.js";
import { imagesUploadImage } from "../funcs/imagesUploadImage.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Images extends ClientSDK {
  /**
   * Upload image
   *
   * @remarks
   * Upload a new image. Supports multipart/form-data with 'file' field.
   */
  async uploadImage(
    request?: operations.UploadImageRequestBody | undefined,
    options?: RequestOptions,
  ): Promise<operations.UploadImageResponse> {
    return unwrapAsync(imagesUploadImage(
      this,
      request,
      options,
    ));
  }

  /**
   * List images
   *
   * @remarks
   * List user's images with pagination and optional path filtering
   */
  async listImages(
    limit?: number | undefined,
    offset?: number | null | undefined,
    path?: string | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListImagesResponse, { offset: number }>> {
    return unwrapResultIterator(imagesListImages(
      this,
      limit,
      offset,
      path,
      options,
    ));
  }

  /**
   * Search images
   *
   * @remarks
   * Search images by filename
   */
  async searchImages(
    q: string,
    limit?: number | undefined,
    options?: RequestOptions,
  ): Promise<operations.SearchImagesResponse> {
    return unwrapAsync(imagesSearchImages(
      this,
      q,
      limit,
      options,
    ));
  }

  /**
   * Get image metadata
   *
   * @remarks
   * Get metadata for a specific image
   */
  async getImage(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.GetImageResponse> {
    return unwrapAsync(imagesGetImage(
      this,
      id,
      options,
    ));
  }

  /**
   * Delete image
   *
   * @remarks
   * Delete an image and all its paths
   */
  async deleteImage(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.DeleteImageResponse> {
    return unwrapAsync(imagesDeleteImage(
      this,
      id,
      options,
    ));
  }

  /**
   * Create signed URL
   *
   * @remarks
   * Create a time-limited signed URL for an image (Pro plan only)
   */
  async createSignedUrl(
    id: string,
    body?: components.CreateSignedUrlRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.CreateSignedUrlResponse> {
    return unwrapAsync(imagesCreateSignedUrl(
      this,
      id,
      body,
      options,
    ));
  }

  /**
   * Delete image path
   *
   * @remarks
   * Delete a specific path from an image. If this is the last path, the image is deleted.
   */
  async deleteImagePath(
    username: string,
    filepath: string,
    options?: RequestOptions,
  ): Promise<operations.DeleteImagePathResponse> {
    return unwrapAsync(imagesDeleteImagePath(
      this,
      username,
      filepath,
      options,
    ));
  }
}
