/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { presetsCreatePreset } from "../funcs/presetsCreatePreset.js";
import { presetsDeletePreset } from "../funcs/presetsDeletePreset.js";
import { presetsGetPreset } from "../funcs/presetsGetPreset.js";
import { presetsListPresets } from "../funcs/presetsListPresets.js";
import { presetsUpdatePreset } from "../funcs/presetsUpdatePreset.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Presets extends ClientSDK {
  /**
   * List presets
   *
   * @remarks
   * Returns all transformation presets for the authenticated user. Requires Pro plan.
   */
  async listPresets(
    options?: RequestOptions,
  ): Promise<operations.ListPresetsResponse> {
    return unwrapAsync(presetsListPresets(
      this,
      options,
    ));
  }

  /**
   * Create preset
   *
   * @remarks
   * Creates a new transformation preset. Requires Pro plan.
   */
  async createPreset(
    request?: components.CreatePresetRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.CreatePresetResponse> {
    return unwrapAsync(presetsCreatePreset(
      this,
      request,
      options,
    ));
  }

  /**
   * Get preset
   *
   * @remarks
   * Returns a specific preset by ID. Requires Pro plan.
   */
  async getPreset(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.GetPresetResponse> {
    return unwrapAsync(presetsGetPreset(
      this,
      id,
      options,
    ));
  }

  /**
   * Update preset
   *
   * @remarks
   * Updates an existing preset. Requires Pro plan.
   */
  async updatePreset(
    id: string,
    body?: components.UpdatePresetRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.UpdatePresetResponse> {
    return unwrapAsync(presetsUpdatePreset(
      this,
      id,
      body,
      options,
    ));
  }

  /**
   * Delete preset
   *
   * @remarks
   * Deletes a preset. Requires Pro plan.
   */
  async deletePreset(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.DeletePresetResponse> {
    return unwrapAsync(presetsDeletePreset(
      this,
      id,
      options,
    ));
  }
}
