/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Images } from "./images.js";
import { Presets } from "./presets.js";
import { Settings } from "./settings.js";
import { Usage } from "./usage.js";

export class Imgsrc extends ClientSDK {
  private _settings?: Settings;
  get settings(): Settings {
    return (this._settings ??= new Settings(this._options));
  }

  private _presets?: Presets;
  get presets(): Presets {
    return (this._presets ??= new Presets(this._options));
  }

  private _usage?: Usage;
  get usage(): Usage {
    return (this._usage ??= new Usage(this._options));
  }

  private _images?: Images;
  get images(): Images {
    return (this._images ??= new Images(this._options));
  }
}
