/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { settingsGetSettings } from "../funcs/settingsGetSettings.js";
import { settingsUpdateSettings } from "../funcs/settingsUpdateSettings.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Settings extends ClientSDK {
  /**
   * Get user settings
   *
   * @remarks
   * Returns the authenticated user's settings
   */
  async getSettings(
    options?: RequestOptions,
  ): Promise<operations.GetSettingsResponse> {
    return unwrapAsync(settingsGetSettings(
      this,
      options,
    ));
  }

  /**
   * Update user settings
   *
   * @remarks
   * Updates the authenticated user's settings
   */
  async updateSettings(
    request?: components.UpdateSettingsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.UpdateSettingsResponse> {
    return unwrapAsync(settingsUpdateSettings(
      this,
      request,
      options,
    ));
  }
}
