/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usageGetUsage } from "../funcs/usageGetUsage.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Usage extends ClientSDK {
  /**
   * Get usage statistics
   *
   * @remarks
   * Returns usage statistics for the authenticated user
   */
  async getUsage(
    options?: RequestOptions,
  ): Promise<operations.GetUsageResponse> {
    return unwrapAsync(usageGetUsage(
      this,
      options,
    ));
  }
}
