/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @img-src/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx settingsGetSettings.example.ts
 */

import { Imgsrc } from "@img-src/sdk";

const imgsrc = new Imgsrc({
  bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
});

async function main() {
  const result = await imgsrc.settings.getSettings();

  console.log(result);
}

main().catch(console.error);
