/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreatePresetResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Preset created
   */
  preset?: components.Preset | undefined;
};

/** @internal */
export const CreatePresetResponse$inboundSchema: z.ZodMiniType<
  CreatePresetResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    Preset: types.optional(components.Preset$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "Preset": "preset",
    });
  }),
);

export function createPresetResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreatePresetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePresetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePresetResponse' from JSON`,
  );
}
