/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateSignedUrlRequest = {
  id: string;
  body?: components.CreateSignedUrlRequest | undefined;
};

export type CreateSignedUrlResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Signed URL created
   */
  signedUrlResponse?: components.SignedUrlResponse | undefined;
};

/** @internal */
export type CreateSignedUrlRequest$Outbound = {
  id: string;
  body?: components.CreateSignedUrlRequest$Outbound | undefined;
};

/** @internal */
export const CreateSignedUrlRequest$outboundSchema: z.ZodMiniType<
  CreateSignedUrlRequest$Outbound,
  CreateSignedUrlRequest
> = z.object({
  id: z.string(),
  body: z.optional(components.CreateSignedUrlRequest$outboundSchema),
});

export function createSignedUrlRequestToJSON(
  createSignedUrlRequest: CreateSignedUrlRequest,
): string {
  return JSON.stringify(
    CreateSignedUrlRequest$outboundSchema.parse(createSignedUrlRequest),
  );
}

/** @internal */
export const CreateSignedUrlResponse$inboundSchema: z.ZodMiniType<
  CreateSignedUrlResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    SignedUrlResponse: types.optional(
      components.SignedUrlResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "SignedUrlResponse": "signedUrlResponse",
    });
  }),
);

export function createSignedUrlResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateSignedUrlResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSignedUrlResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSignedUrlResponse' from JSON`,
  );
}
