/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteImageRequest = {
  id: string;
};

export type DeleteImageResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Image deleted
   */
  deleteResponse?: components.DeleteResponse | undefined;
};

/** @internal */
export type DeleteImageRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteImageRequest$outboundSchema: z.ZodMiniType<
  DeleteImageRequest$Outbound,
  DeleteImageRequest
> = z.object({
  id: z.string(),
});

export function deleteImageRequestToJSON(
  deleteImageRequest: DeleteImageRequest,
): string {
  return JSON.stringify(
    DeleteImageRequest$outboundSchema.parse(deleteImageRequest),
  );
}

/** @internal */
export const DeleteImageResponse$inboundSchema: z.ZodMiniType<
  DeleteImageResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    DeleteResponse: types.optional(components.DeleteResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "DeleteResponse": "deleteResponse",
    });
  }),
);

export function deleteImageResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteImageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteImageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteImageResponse' from JSON`,
  );
}
