/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeletePresetRequest = {
  id: string;
};

export type DeletePresetResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Preset deleted
   */
  deletePresetResponse?: components.DeletePresetResponse | undefined;
};

/** @internal */
export type DeletePresetRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeletePresetRequest$outboundSchema: z.ZodMiniType<
  DeletePresetRequest$Outbound,
  DeletePresetRequest
> = z.object({
  id: z.string(),
});

export function deletePresetRequestToJSON(
  deletePresetRequest: DeletePresetRequest,
): string {
  return JSON.stringify(
    DeletePresetRequest$outboundSchema.parse(deletePresetRequest),
  );
}

/** @internal */
export const DeletePresetResponse$inboundSchema: z.ZodMiniType<
  DeletePresetResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    DeletePresetResponse: types.optional(
      components.DeletePresetResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "DeletePresetResponse": "deletePresetResponse",
    });
  }),
);

export function deletePresetResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeletePresetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeletePresetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeletePresetResponse' from JSON`,
  );
}
