/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteImagePathRequest = {
  username: string;
  filepath: string;
};

export type DeleteImagePathResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Path deleted
   */
  pathDeleteResponse?: components.PathDeleteResponse | undefined;
};

/** @internal */
export type DeleteImagePathRequest$Outbound = {
  username: string;
  filepath: string;
};

/** @internal */
export const DeleteImagePathRequest$outboundSchema: z.ZodMiniType<
  DeleteImagePathRequest$Outbound,
  DeleteImagePathRequest
> = z.object({
  username: z.string(),
  filepath: z.string(),
});

export function deleteImagePathRequestToJSON(
  deleteImagePathRequest: DeleteImagePathRequest,
): string {
  return JSON.stringify(
    DeleteImagePathRequest$outboundSchema.parse(deleteImagePathRequest),
  );
}

/** @internal */
export const DeleteImagePathResponse$inboundSchema: z.ZodMiniType<
  DeleteImagePathResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    PathDeleteResponse: types.optional(
      components.PathDeleteResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "PathDeleteResponse": "pathDeleteResponse",
    });
  }),
);

export function deleteImagePathResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteImagePathResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteImagePathResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteImagePathResponse' from JSON`,
  );
}
