/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetImageRequest = {
  id: string;
};

export type GetImageResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Image metadata
   */
  metadataResponse?: components.MetadataResponse | undefined;
};

/** @internal */
export type GetImageRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetImageRequest$outboundSchema: z.ZodMiniType<
  GetImageRequest$Outbound,
  GetImageRequest
> = z.object({
  id: z.string(),
});

export function getImageRequestToJSON(
  getImageRequest: GetImageRequest,
): string {
  return JSON.stringify(GetImageRequest$outboundSchema.parse(getImageRequest));
}

/** @internal */
export const GetImageResponse$inboundSchema: z.ZodMiniType<
  GetImageResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    MetadataResponse: types.optional(components.MetadataResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "MetadataResponse": "metadataResponse",
    });
  }),
);

export function getImageResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetImageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetImageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetImageResponse' from JSON`,
  );
}
