/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetPresetRequest = {
  id: string;
};

export type GetPresetResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Preset details
   */
  preset?: components.Preset | undefined;
};

/** @internal */
export type GetPresetRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetPresetRequest$outboundSchema: z.ZodMiniType<
  GetPresetRequest$Outbound,
  GetPresetRequest
> = z.object({
  id: z.string(),
});

export function getPresetRequestToJSON(
  getPresetRequest: GetPresetRequest,
): string {
  return JSON.stringify(
    GetPresetRequest$outboundSchema.parse(getPresetRequest),
  );
}

/** @internal */
export const GetPresetResponse$inboundSchema: z.ZodMiniType<
  GetPresetResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    Preset: types.optional(components.Preset$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "Preset": "preset",
    });
  }),
);

export function getPresetResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPresetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPresetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPresetResponse' from JSON`,
  );
}
