/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetSettingsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * User settings
   */
  settingsResponse?: components.SettingsResponse | undefined;
};

/** @internal */
export const GetSettingsResponse$inboundSchema: z.ZodMiniType<
  GetSettingsResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    SettingsResponse: types.optional(components.SettingsResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "SettingsResponse": "settingsResponse",
    });
  }),
);

export function getSettingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSettingsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSettingsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSettingsResponse' from JSON`,
  );
}
