/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetUsageResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Usage statistics
   */
  usageResponse?: components.UsageResponse | undefined;
};

/** @internal */
export const GetUsageResponse$inboundSchema: z.ZodMiniType<
  GetUsageResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    UsageResponse: types.optional(components.UsageResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "UsageResponse": "usageResponse",
    });
  }),
);

export function getUsageResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUsageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUsageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUsageResponse' from JSON`,
  );
}
