/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListImagesRequest = {
  limit?: number | undefined;
  offset?: number | null | undefined;
  path?: string | undefined;
};

export type ListImagesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * List of images
   */
  imageListResponse?: components.ImageListResponse | undefined;
};

/** @internal */
export type ListImagesRequest$Outbound = {
  limit: number;
  offset: number | null;
  path?: string | undefined;
};

/** @internal */
export const ListImagesRequest$outboundSchema: z.ZodMiniType<
  ListImagesRequest$Outbound,
  ListImagesRequest
> = z.object({
  limit: z._default(z.int(), 50),
  offset: z.nullable(z._default(z.int(), 0)),
  path: z.optional(z.string()),
});

export function listImagesRequestToJSON(
  listImagesRequest: ListImagesRequest,
): string {
  return JSON.stringify(
    ListImagesRequest$outboundSchema.parse(listImagesRequest),
  );
}

/** @internal */
export const ListImagesResponse$inboundSchema: z.ZodMiniType<
  ListImagesResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    ImageListResponse: types.optional(
      components.ImageListResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "ImageListResponse": "imageListResponse",
    });
  }),
);

export function listImagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListImagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListImagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListImagesResponse' from JSON`,
  );
}
