/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListPresetsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * List of presets
   */
  listPresetsResponse?: components.ListPresetsResponse | undefined;
};

/** @internal */
export const ListPresetsResponse$inboundSchema: z.ZodMiniType<
  ListPresetsResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    ListPresetsResponse: types.optional(
      components.ListPresetsResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "ListPresetsResponse": "listPresetsResponse",
    });
  }),
);

export function listPresetsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPresetsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPresetsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPresetsResponse' from JSON`,
  );
}
