/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SearchImagesRequest = {
  q: string;
  limit?: number | undefined;
};

export type SearchImagesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Search results
   */
  searchResponse?: components.SearchResponse | undefined;
};

/** @internal */
export type SearchImagesRequest$Outbound = {
  q: string;
  limit: number;
};

/** @internal */
export const SearchImagesRequest$outboundSchema: z.ZodMiniType<
  SearchImagesRequest$Outbound,
  SearchImagesRequest
> = z.object({
  q: z.string(),
  limit: z._default(z.int(), 20),
});

export function searchImagesRequestToJSON(
  searchImagesRequest: SearchImagesRequest,
): string {
  return JSON.stringify(
    SearchImagesRequest$outboundSchema.parse(searchImagesRequest),
  );
}

/** @internal */
export const SearchImagesResponse$inboundSchema: z.ZodMiniType<
  SearchImagesResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    SearchResponse: types.optional(components.SearchResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "SearchResponse": "searchResponse",
    });
  }),
);

export function searchImagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchImagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchImagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchImagesResponse' from JSON`,
  );
}
