/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateSettingsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Updated user settings
   */
  settingsUpdateResponse?: components.SettingsUpdateResponse | undefined;
};

/** @internal */
export const UpdateSettingsResponse$inboundSchema: z.ZodMiniType<
  UpdateSettingsResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    SettingsUpdateResponse: types.optional(
      components.SettingsUpdateResponse$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "SettingsUpdateResponse": "settingsUpdateResponse",
    });
  }),
);

export function updateSettingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateSettingsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateSettingsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateSettingsResponse' from JSON`,
  );
}
