/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdatePresetRequest = {
  id: string;
  body?: components.UpdatePresetRequest | undefined;
};

export type UpdatePresetResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Preset updated
   */
  preset?: components.Preset | undefined;
};

/** @internal */
export type UpdatePresetRequest$Outbound = {
  id: string;
  body?: components.UpdatePresetRequest$Outbound | undefined;
};

/** @internal */
export const UpdatePresetRequest$outboundSchema: z.ZodMiniType<
  UpdatePresetRequest$Outbound,
  UpdatePresetRequest
> = z.object({
  id: z.string(),
  body: z.optional(components.UpdatePresetRequest$outboundSchema),
});

export function updatePresetRequestToJSON(
  updatePresetRequest: UpdatePresetRequest,
): string {
  return JSON.stringify(
    UpdatePresetRequest$outboundSchema.parse(updatePresetRequest),
  );
}

/** @internal */
export const UpdatePresetResponse$inboundSchema: z.ZodMiniType<
  UpdatePresetResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    Preset: types.optional(components.Preset$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "Preset": "preset",
    });
  }),
);

export function updatePresetResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePresetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePresetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePresetResponse' from JSON`,
  );
}
