/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { blobLikeSchema } from "../../types/blobs.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FileT = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type UploadImageRequestBody = {
  /**
   * Image file to upload
   */
  file?: FileT | Blob | undefined;
  /**
   * Target path for organizing the image
   */
  targetPath?: string | undefined;
};

export type UploadImageResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Image uploaded successfully
   */
  uploadResponse?: components.UploadResponse | undefined;
};

/** @internal */
export type FileT$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const FileT$outboundSchema: z.ZodMiniType<FileT$Outbound, FileT> = z
  .object({
    fileName: z.string(),
    content: z.union([
      z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
      z.custom<Blob>(x => x instanceof Blob),
      z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
      z.custom<Uint8Array>(x => x instanceof Uint8Array),
    ]),
  });

export function fileToJSON(fileT: FileT): string {
  return JSON.stringify(FileT$outboundSchema.parse(fileT));
}

/** @internal */
export type UploadImageRequestBody$Outbound = {
  file?: FileT$Outbound | Blob | undefined;
  target_path?: string | undefined;
};

/** @internal */
export const UploadImageRequestBody$outboundSchema: z.ZodMiniType<
  UploadImageRequestBody$Outbound,
  UploadImageRequestBody
> = z.pipe(
  z.object({
    file: z.optional(
      z.union([z.lazy(() => FileT$outboundSchema), blobLikeSchema]),
    ),
    targetPath: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      targetPath: "target_path",
    });
  }),
);

export function uploadImageRequestBodyToJSON(
  uploadImageRequestBody: UploadImageRequestBody,
): string {
  return JSON.stringify(
    UploadImageRequestBody$outboundSchema.parse(uploadImageRequestBody),
  );
}

/** @internal */
export const UploadImageResponse$inboundSchema: z.ZodMiniType<
  UploadImageResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    UploadResponse: types.optional(components.UploadResponse$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "UploadResponse": "uploadResponse",
    });
  }),
);

export function uploadImageResponseFromJSON(
  jsonString: string,
): SafeParseResult<UploadImageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadImageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadImageResponse' from JSON`,
  );
}
