/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AvailableFormats = {
  /**
   * WebP format URL
   */
  webp: string;
  /**
   * AVIF format URL
   */
  avif: string;
  /**
   * JPEG format URL
   */
  jpeg: string;
};

/** @internal */
export const AvailableFormats$inboundSchema: z.ZodMiniType<
  AvailableFormats,
  unknown
> = z.object({
  webp: types.string(),
  avif: types.string(),
  jpeg: types.string(),
});

export function availableFormatsFromJSON(
  jsonString: string,
): SafeParseResult<AvailableFormats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AvailableFormats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AvailableFormats' from JSON`,
  );
}
