/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CdnUrls = {
  /**
   * Original format URL
   */
  original: string;
  /**
   * WebP format URL
   */
  webp: string;
  /**
   * AVIF format URL
   */
  avif: string;
  /**
   * JPEG format URL
   */
  jpeg: string;
  /**
   * PNG format URL
   */
  png: string;
  /**
   * JPEG XL format URL
   */
  jxl: string;
};

/** @internal */
export const CdnUrls$inboundSchema: z.ZodMiniType<CdnUrls, unknown> = z.object({
  original: types.string(),
  webp: types.string(),
  avif: types.string(),
  jpeg: types.string(),
  png: types.string(),
  jxl: types.string(),
});

export function cdnUrlsFromJSON(
  jsonString: string,
): SafeParseResult<CdnUrls, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CdnUrls$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CdnUrls' from JSON`,
  );
}
