/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CreateSignedUrlRequest = {
  /**
   * Expiration time in seconds (60-604800, default 3600)
   */
  expiresInSeconds?: number | undefined;
};

/** @internal */
export type CreateSignedUrlRequest$Outbound = {
  expires_in_seconds: number;
};

/** @internal */
export const CreateSignedUrlRequest$outboundSchema: z.ZodMiniType<
  CreateSignedUrlRequest$Outbound,
  CreateSignedUrlRequest
> = z.pipe(
  z.object({
    expiresInSeconds: z._default(z.int(), 3600),
  }),
  z.transform((v) => {
    return remap$(v, {
      expiresInSeconds: "expires_in_seconds",
    });
  }),
);

export function createSignedUrlRequestToJSON(
  createSignedUrlRequest: CreateSignedUrlRequest,
): string {
  return JSON.stringify(
    CreateSignedUrlRequest$outboundSchema.parse(createSignedUrlRequest),
  );
}
