/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreatePresetRequest = {
  /**
   * Preset name (1-50 characters)
   */
  name: string;
  /**
   * Optional description (max 200 characters)
   */
  description?: string | undefined;
  /**
   * Transformation parameters
   */
  params: { [k: string]: any | null };
};

/** @internal */
export type CreatePresetRequest$Outbound = {
  name: string;
  description?: string | undefined;
  params: { [k: string]: any | null };
};

/** @internal */
export const CreatePresetRequest$outboundSchema: z.ZodMiniType<
  CreatePresetRequest$Outbound,
  CreatePresetRequest
> = z.object({
  name: z.string(),
  description: z.optional(z.string()),
  params: z.record(z.string(), z.nullable(z.any())),
});

export function createPresetRequestToJSON(
  createPresetRequest: CreatePresetRequest,
): string {
  return JSON.stringify(
    CreatePresetRequest$outboundSchema.parse(createPresetRequest),
  );
}
