/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const Fit = {
  Cover: "cover",
  Contain: "contain",
  Fill: "fill",
  ScaleDown: "scale-down",
} as const;
export type Fit = ClosedEnum<typeof Fit>;

export const Format = {
  Webp: "webp",
  Avif: "avif",
  Jpeg: "jpeg",
  Png: "png",
} as const;
export type Format = ClosedEnum<typeof Format>;

/**
 * Optional image transformation parameters
 */
export type Transformation = {
  width?: number | undefined;
  height?: number | undefined;
  fit?: Fit | undefined;
  quality?: number | undefined;
  format?: Format | undefined;
};

export type CreateSignedUrlRequest = {
  /**
   * Expiration time in seconds (60-86400, default 3600)
   */
  expiresInSeconds?: number | undefined;
  /**
   * Optional image transformation parameters
   */
  transformation?: Transformation | undefined;
};

/** @internal */
export const Fit$outboundSchema: z.ZodMiniEnum<typeof Fit> = z.enum(Fit);

/** @internal */
export const Format$outboundSchema: z.ZodMiniEnum<typeof Format> = z.enum(
  Format,
);

/** @internal */
export type Transformation$Outbound = {
  width?: number | undefined;
  height?: number | undefined;
  fit?: string | undefined;
  quality?: number | undefined;
  format?: string | undefined;
};

/** @internal */
export const Transformation$outboundSchema: z.ZodMiniType<
  Transformation$Outbound,
  Transformation
> = z.object({
  width: z.optional(z.int()),
  height: z.optional(z.int()),
  fit: z.optional(Fit$outboundSchema),
  quality: z.optional(z.int()),
  format: z.optional(Format$outboundSchema),
});

export function transformationToJSON(transformation: Transformation): string {
  return JSON.stringify(Transformation$outboundSchema.parse(transformation));
}

/** @internal */
export type CreateSignedUrlRequest$Outbound = {
  expires_in_seconds: number;
  transformation?: Transformation$Outbound | undefined;
};

/** @internal */
export const CreateSignedUrlRequest$outboundSchema: z.ZodMiniType<
  CreateSignedUrlRequest$Outbound,
  CreateSignedUrlRequest
> = z.pipe(
  z.object({
    expiresInSeconds: z._default(z.int(), 3600),
    transformation: z.optional(z.lazy(() => Transformation$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      expiresInSeconds: "expires_in_seconds",
    });
  }),
);

export function createSignedUrlRequestToJSON(
  createSignedUrlRequest: CreateSignedUrlRequest,
): string {
  return JSON.stringify(
    CreateSignedUrlRequest$outboundSchema.parse(createSignedUrlRequest),
  );
}
