/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Credits = {
  /**
   * Storage bytes used
   */
  storageBytes: number;
  /**
   * API requests made in current period
   */
  apiRequests: number;
  /**
   * Transformations performed in current period
   */
  transformations: number;
};

/** @internal */
export const Credits$inboundSchema: z.ZodMiniType<Credits, unknown> = z.pipe(
  z.object({
    storage_bytes: types.number(),
    api_requests: types.number(),
    transformations: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "storage_bytes": "storageBytes",
      "api_requests": "apiRequests",
    });
  }),
);

export function creditsFromJSON(
  jsonString: string,
): SafeParseResult<Credits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Credits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Credits' from JSON`,
  );
}
