/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CurrentPeriod = {
  /**
   * Period identifier (YYYY-MM format)
   */
  period: string;
  /**
   * Unix timestamp of period start
   */
  periodStart: number;
  /**
   * Unix timestamp of period end
   */
  periodEnd: number;
  /**
   * Uploads this period
   */
  uploads: number;
  /**
   * Bandwidth used this period in bytes
   */
  bandwidthBytes: number;
  /**
   * API requests this period
   */
  apiRequests: number;
  /**
   * Image transformations this period
   */
  transformations: number;
};

/** @internal */
export const CurrentPeriod$inboundSchema: z.ZodMiniType<
  CurrentPeriod,
  unknown
> = z.pipe(
  z.object({
    period: types.string(),
    period_start: types.number(),
    period_end: types.number(),
    uploads: types.number(),
    bandwidth_bytes: types.number(),
    api_requests: types.number(),
    transformations: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "period_start": "periodStart",
      "period_end": "periodEnd",
      "bandwidth_bytes": "bandwidthBytes",
      "api_requests": "apiRequests",
    });
  }),
);

export function currentPeriodFromJSON(
  jsonString: string,
): SafeParseResult<CurrentPeriod, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CurrentPeriod$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CurrentPeriod' from JSON`,
  );
}
