/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeletePresetResponse = {
  /**
   * Operation success flag
   */
  success: boolean;
  /**
   * Human-readable message
   */
  message: string;
};

/** @internal */
export const DeletePresetResponse$inboundSchema: z.ZodMiniType<
  DeletePresetResponse,
  unknown
> = z.object({
  success: types.boolean(),
  message: types.string(),
});

export function deletePresetResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeletePresetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeletePresetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeletePresetResponse' from JSON`,
  );
}
