/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteResponse = {
  /**
   * Operation success flag
   */
  success: boolean;
  /**
   * Human-readable message
   */
  message: string;
  /**
   * List of deleted paths
   */
  deletedPaths?: Array<string> | undefined;
  /**
   * Deletion timestamp
   */
  deletedAt: Date;
};

/** @internal */
export const DeleteResponse$inboundSchema: z.ZodMiniType<
  DeleteResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    message: types.string(),
    deleted_paths: types.optional(z.array(types.string())),
    deleted_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "deleted_paths": "deletedPaths",
      "deleted_at": "deletedAt",
    });
  }),
);

export function deleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteResponse' from JSON`,
  );
}
