/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ErrorDetail = {
  /**
   * Error code (e.g., NOT_FOUND, UNAUTHORIZED, VALIDATION_ERROR)
   */
  code: string;
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * HTTP status code
   */
  status: number;
  /**
   * Request path (optional)
   */
  path?: string | undefined;
};

/** @internal */
export const ErrorDetail$inboundSchema: z.ZodMiniType<ErrorDetail, unknown> = z
  .object({
    code: types.string(),
    message: types.string(),
    status: types.number(),
    path: types.optional(types.string()),
  });

export function errorDetailFromJSON(
  jsonString: string,
): SafeParseResult<ErrorDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorDetail' from JSON`,
  );
}
