/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FolderItem = {
  /**
   * Folder name
   */
  name: string;
  /**
   * Number of images in folder (including subfolders)
   */
  imageCount: number;
};

/** @internal */
export const FolderItem$inboundSchema: z.ZodMiniType<FolderItem, unknown> = z
  .pipe(
    z.object({
      name: types.string(),
      image_count: types.number(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "image_count": "imageCount",
      });
    }),
  );

export function folderItemFromJSON(
  jsonString: string,
): SafeParseResult<FolderItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FolderItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FolderItem' from JSON`,
  );
}
