/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type HateoasLinks = {
  /**
   * Link to the resource itself
   */
  self: string;
  /**
   * Link to delete the resource
   */
  delete: string;
};

/** @internal */
export const HateoasLinks$inboundSchema: z.ZodMiniType<HateoasLinks, unknown> =
  z.object({
    self: types.string(),
    delete: types.string(),
  });

export function hateoasLinksFromJSON(
  jsonString: string,
): SafeParseResult<HateoasLinks, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HateoasLinks$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HateoasLinks' from JSON`,
  );
}
