/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ImageMetadata = {
  /**
   * Full SHA256 hash
   */
  hash: string;
  /**
   * Original filename as uploaded
   */
  originalFilename: string;
  /**
   * File size in bytes
   */
  size: number;
  /**
   * Upload timestamp
   */
  uploadedAt: Date;
  /**
   * MIME type
   */
  mimeType: string;
  /**
   * Image width in pixels
   */
  width?: number | undefined;
  /**
   * Image height in pixels
   */
  height?: number | undefined;
  /**
   * Dominant color as 6-digit hex (without #)
   */
  dominantColor?: string | undefined;
};

/** @internal */
export const ImageMetadata$inboundSchema: z.ZodMiniType<
  ImageMetadata,
  unknown
> = z.pipe(
  z.object({
    hash: types.string(),
    original_filename: types.string(),
    size: types.number(),
    uploaded_at: types.date(),
    mime_type: types.string(),
    width: types.optional(types.number()),
    height: types.optional(types.number()),
    dominant_color: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "original_filename": "originalFilename",
      "uploaded_at": "uploadedAt",
      "mime_type": "mimeType",
      "dominant_color": "dominantColor",
    });
  }),
);

export function imageMetadataFromJSON(
  jsonString: string,
): SafeParseResult<ImageMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageMetadata' from JSON`,
  );
}
