/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ImageDimensions = {
  /**
   * Image width in pixels
   */
  width: number;
  /**
   * Image height in pixels
   */
  height: number;
};

/** @internal */
export const ImageDimensions$inboundSchema: z.ZodMiniType<
  ImageDimensions,
  unknown
> = z.object({
  width: types.number(),
  height: types.number(),
});

export function imageDimensionsFromJSON(
  jsonString: string,
): SafeParseResult<ImageDimensions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageDimensions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageDimensions' from JSON`,
  );
}
