/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ActiveSignedUrl,
  ActiveSignedUrl$inboundSchema,
} from "./activesignedurl.js";
import {
  Visibility,
  Visibility$inboundSchema,
} from "./visibility.js";

export type ImageListItem = {
  /**
   * Image ID
   */
  id: string;
  /**
   * Original filename as uploaded
   */
  originalFilename: string;
  /**
   * Sanitized filename (URL-safe)
   */
  sanitizedFilename?: string | undefined;
  /**
   * File size in bytes
   */
  size: number;
  /**
   * Upload timestamp
   */
  uploadedAt: Date;
  /**
   * API endpoint URL
   */
  url: string;
  /**
   * CDN URL for direct access
   */
  cdnUrl?: string | undefined;
  /**
   * All paths for this image
   */
  paths: Array<string>;
  /**
   * Image visibility setting
   */
  visibility: Visibility;
  /**
   * Active signed URL (if available)
   */
  activeSignedUrl?: ActiveSignedUrl | undefined;
};

/** @internal */
export const ImageListItem$inboundSchema: z.ZodMiniType<
  ImageListItem,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    original_filename: types.string(),
    sanitized_filename: types.optional(types.string()),
    size: types.number(),
    uploaded_at: types.date(),
    url: types.string(),
    cdn_url: types.optional(types.string()),
    paths: z.array(types.string()),
    visibility: Visibility$inboundSchema,
    active_signed_url: types.optional(ActiveSignedUrl$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "original_filename": "originalFilename",
      "sanitized_filename": "sanitizedFilename",
      "uploaded_at": "uploadedAt",
      "cdn_url": "cdnUrl",
      "active_signed_url": "activeSignedUrl",
    });
  }),
);

export function imageListItemFromJSON(
  jsonString: string,
): SafeParseResult<ImageListItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageListItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageListItem' from JSON`,
  );
}
