/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { FolderItem, FolderItem$inboundSchema } from "./folderitem.js";
import { ImageListItem, ImageListItem$inboundSchema } from "./imagelistitem.js";

export type ImageListResponse = {
  images: Array<ImageListItem>;
  folders: Array<FolderItem>;
  /**
   * Total count of images (in current path)
   */
  total: number;
  /**
   * Maximum items per page
   */
  limit: number;
  /**
   * Current offset
   */
  offset: number;
  /**
   * Whether more items exist
   */
  hasMore: boolean;
  /**
   * Current path filter (if any)
   */
  pathFilter?: string | undefined;
};

/** @internal */
export const ImageListResponse$inboundSchema: z.ZodMiniType<
  ImageListResponse,
  unknown
> = z.pipe(
  z.object({
    images: z.array(ImageListItem$inboundSchema),
    folders: z.array(FolderItem$inboundSchema),
    total: types.number(),
    limit: types.number(),
    offset: types.number(),
    has_more: types.boolean(),
    path_filter: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "has_more": "hasMore",
      "path_filter": "pathFilter",
    });
  }),
);

export function imageListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ImageListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageListResponse' from JSON`,
  );
}
