/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Preset, Preset$inboundSchema } from "./preset.js";

export type ListPresetsResponse = {
  presets: Array<Preset>;
  /**
   * Total number of presets
   */
  total: number;
};

/** @internal */
export const ListPresetsResponse$inboundSchema: z.ZodMiniType<
  ListPresetsResponse,
  unknown
> = z.object({
  presets: z.array(Preset$inboundSchema),
  total: types.number(),
});

export function listPresetsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPresetsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPresetsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPresetsResponse' from JSON`,
  );
}
