/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { CdnUrls, CdnUrls$inboundSchema } from "./cdnurls.js";
import { HateoasLinks, HateoasLinks$inboundSchema } from "./hateoaslinks.js";
import { ImageMetadata, ImageMetadata$inboundSchema } from "./imagemetadata.js";
import {
  Visibility,
  Visibility$inboundSchema,
} from "./visibility.js";

export type MetadataResponse = {
  /**
   * Image ID
   */
  id: string;
  metadata: ImageMetadata;
  /**
   * Image visibility setting
   */
  visibility: Visibility;
  urls: CdnUrls;
  links: HateoasLinks;
};

/** @internal */
export const MetadataResponse$inboundSchema: z.ZodMiniType<
  MetadataResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    metadata: ImageMetadata$inboundSchema,
    visibility: Visibility$inboundSchema,
    urls: CdnUrls$inboundSchema,
    _links: HateoasLinks$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "_links": "links",
    });
  }),
);

export function metadataResponseFromJSON(
  jsonString: string,
): SafeParseResult<MetadataResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetadataResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetadataResponse' from JSON`,
  );
}
