/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PathDeleteResponse = {
  /**
   * Operation success flag
   */
  success: boolean;
  /**
   * Human-readable message
   */
  message: string;
  /**
   * Remaining paths for the image
   */
  remainingPaths: Array<string>;
  /**
   * Whether the image itself was deleted (last path removed)
   */
  imageDeleted: boolean;
  /**
   * Deletion timestamp
   */
  deletedAt: Date;
};

/** @internal */
export const PathDeleteResponse$inboundSchema: z.ZodMiniType<
  PathDeleteResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.boolean(),
    message: types.string(),
    remaining_paths: z.array(types.string()),
    image_deleted: types.boolean(),
    deleted_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "remaining_paths": "remainingPaths",
      "image_deleted": "imageDeleted",
      "deleted_at": "deletedAt",
    });
  }),
);

export function pathDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<PathDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PathDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PathDeleteResponse' from JSON`,
  );
}
