/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PlanLimits = {
  /**
   * Maximum uploads per month (null = unlimited)
   */
  maxUploadsPerMonth: number | null;
  /**
   * Maximum storage in bytes (null = unlimited)
   */
  maxStorageBytes: number | null;
  /**
   * Maximum bandwidth per month in bytes (null = unlimited)
   */
  maxBandwidthPerMonth: number | null;
  /**
   * Maximum API requests per month (null = unlimited)
   */
  maxApiRequestsPerMonth: number | null;
  /**
   * Maximum image transformations per month (null = unlimited)
   */
  maxTransformationsPerMonth: number | null;
};

/** @internal */
export const PlanLimits$inboundSchema: z.ZodMiniType<PlanLimits, unknown> = z
  .pipe(
    z.object({
      max_uploads_per_month: types.nullable(types.number()),
      max_storage_bytes: types.nullable(types.number()),
      max_bandwidth_per_month: types.nullable(types.number()),
      max_api_requests_per_month: types.nullable(types.number()),
      max_transformations_per_month: types.nullable(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "max_uploads_per_month": "maxUploadsPerMonth",
        "max_storage_bytes": "maxStorageBytes",
        "max_bandwidth_per_month": "maxBandwidthPerMonth",
        "max_api_requests_per_month": "maxApiRequestsPerMonth",
        "max_transformations_per_month": "maxTransformationsPerMonth",
      });
    }),
  );

export function planLimitsFromJSON(
  jsonString: string,
): SafeParseResult<PlanLimits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlanLimits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlanLimits' from JSON`,
  );
}
