/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Preset = {
  /**
   * Preset ID
   */
  id: string;
  /**
   * Preset name
   */
  name: string;
  /**
   * Optional description
   */
  description: string | null;
  /**
   * Transformation parameters
   */
  params: { [k: string]: any | null };
  /**
   * Creation timestamp (Unix epoch)
   */
  createdAt: number;
  /**
   * Last update timestamp (Unix epoch)
   */
  updatedAt: number;
  /**
   * Number of times this preset has been used
   */
  usageCount: number;
};

/** @internal */
export const Preset$inboundSchema: z.ZodMiniType<Preset, unknown> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    description: types.nullable(types.string()),
    params: z.record(z.string(), types.nullable(z.any())),
    created_at: types.number(),
    updated_at: types.number(),
    usage_count: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "usage_count": "usageCount",
    });
  }),
);

export function presetFromJSON(
  jsonString: string,
): SafeParseResult<Preset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Preset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Preset' from JSON`,
  );
}
