/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SearchResult = {
  /**
   * Image ID
   */
  id: string;
  /**
   * Original filename
   */
  originalFilename: string;
  /**
   * Sanitized filename
   */
  sanitizedFilename?: string | undefined;
  /**
   * All paths for this image
   */
  paths: Array<string>;
  /**
   * File size in bytes
   */
  size: number;
  /**
   * Upload timestamp
   */
  uploadedAt: Date;
  /**
   * API endpoint URL
   */
  url: string;
  /**
   * CDN URL
   */
  cdnUrl?: string | undefined;
};

/** @internal */
export const SearchResult$inboundSchema: z.ZodMiniType<SearchResult, unknown> =
  z.pipe(
    z.object({
      id: types.string(),
      original_filename: types.string(),
      sanitized_filename: types.optional(types.string()),
      paths: z.array(types.string()),
      size: types.number(),
      uploaded_at: types.date(),
      url: types.string(),
      cdn_url: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "original_filename": "originalFilename",
        "sanitized_filename": "sanitizedFilename",
        "uploaded_at": "uploadedAt",
        "cdn_url": "cdnUrl",
      });
    }),
  );

export function searchResultFromJSON(
  jsonString: string,
): SafeParseResult<SearchResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchResult' from JSON`,
  );
}
