/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { SearchResult, SearchResult$inboundSchema } from "./searchresult.js";

export type SearchResponse = {
  results: Array<SearchResult>;
  /**
   * Total number of matches
   */
  total: number;
  /**
   * Original search query
   */
  query: string;
};

/** @internal */
export const SearchResponse$inboundSchema: z.ZodMiniType<
  SearchResponse,
  unknown
> = z.object({
  results: z.array(SearchResult$inboundSchema),
  total: types.number(),
  query: types.string(),
});

export function searchResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchResponse' from JSON`,
  );
}
