/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { UserSettings, UserSettings$inboundSchema } from "./usersettings.js";

export type SettingsUpdateResponse = {
  settings: UserSettings;
  /**
   * Human-readable message
   */
  message: string;
};

/** @internal */
export const SettingsUpdateResponse$inboundSchema: z.ZodMiniType<
  SettingsUpdateResponse,
  unknown
> = z.object({
  settings: UserSettings$inboundSchema,
  message: types.string(),
});

export function settingsUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<SettingsUpdateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SettingsUpdateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SettingsUpdateResponse' from JSON`,
  );
}
