/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SignedUrlResponse = {
  /**
   * Time-limited signed URL
   */
  signedUrl: string;
  /**
   * Expiration timestamp (Unix epoch)
   */
  expiresAt: number;
  /**
   * Seconds until expiration
   */
  expiresInSeconds: number;
};

/** @internal */
export const SignedUrlResponse$inboundSchema: z.ZodMiniType<
  SignedUrlResponse,
  unknown
> = z.pipe(
  z.object({
    signed_url: types.string(),
    expires_at: types.number(),
    expires_in_seconds: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "signed_url": "signedUrl",
      "expires_at": "expiresAt",
      "expires_in_seconds": "expiresInSeconds",
    });
  }),
);

export function signedUrlResponseFromJSON(
  jsonString: string,
): SafeParseResult<SignedUrlResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SignedUrlResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SignedUrlResponse' from JSON`,
  );
}
