/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Visibility,
  Visibility$inboundSchema,
} from "./visibility.js";

export type UpdateVisibilityResponse = {
  /**
   * Image ID
   */
  id: string;
  /**
   * Updated visibility setting
   */
  visibility: Visibility;
  /**
   * Success message
   */
  message: string;
};

/** @internal */
export const UpdateVisibilityResponse$inboundSchema: z.ZodMiniType<
  UpdateVisibilityResponse,
  unknown
> = z.object({
  id: types.string(),
  visibility: Visibility$inboundSchema,
  message: types.string(),
});

export function updateVisibilityResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateVisibilityResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateVisibilityResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateVisibilityResponse' from JSON`,
  );
}
