/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type UpdateSettingsRequest = {
  /**
   * Preferred delivery formats (ordered)
   */
  deliveryFormats?: Array<string> | undefined;
  /**
   * Default image quality (1-100)
   */
  defaultQuality?: number | undefined;
  /**
   * Default fit mode
   */
  defaultFitMode?: string | undefined;
  /**
   * Default maximum width (null to clear)
   */
  defaultMaxWidth?: number | null | undefined;
  /**
   * Default maximum height (null to clear)
   */
  defaultMaxHeight?: number | null | undefined;
  /**
   * UI theme
   */
  theme?: string | undefined;
  /**
   * UI language
   */
  language?: string | undefined;
};

/** @internal */
export type UpdateSettingsRequest$Outbound = {
  delivery_formats?: Array<string> | undefined;
  default_quality?: number | undefined;
  default_fit_mode?: string | undefined;
  default_max_width?: number | null | undefined;
  default_max_height?: number | null | undefined;
  theme?: string | undefined;
  language?: string | undefined;
};

/** @internal */
export const UpdateSettingsRequest$outboundSchema: z.ZodMiniType<
  UpdateSettingsRequest$Outbound,
  UpdateSettingsRequest
> = z.pipe(
  z.object({
    deliveryFormats: z.optional(z.array(z.string())),
    defaultQuality: z.optional(z.int()),
    defaultFitMode: z.optional(z.string()),
    defaultMaxWidth: z.optional(z.nullable(z.int())),
    defaultMaxHeight: z.optional(z.nullable(z.int())),
    theme: z.optional(z.string()),
    language: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      deliveryFormats: "delivery_formats",
      defaultQuality: "default_quality",
      defaultFitMode: "default_fit_mode",
      defaultMaxWidth: "default_max_width",
      defaultMaxHeight: "default_max_height",
    });
  }),
);

export function updateSettingsRequestToJSON(
  updateSettingsRequest: UpdateSettingsRequest,
): string {
  return JSON.stringify(
    UpdateSettingsRequest$outboundSchema.parse(updateSettingsRequest),
  );
}
