/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type UpdatePresetRequest = {
  /**
   * New preset name (1-50 characters)
   */
  name?: string | undefined;
  /**
   * New description (max 200 characters, null to clear)
   */
  description?: string | null | undefined;
  /**
   * New transformation parameters
   */
  params?: { [k: string]: any | null } | undefined;
};

/** @internal */
export type UpdatePresetRequest$Outbound = {
  name?: string | undefined;
  description?: string | null | undefined;
  params?: { [k: string]: any | null } | undefined;
};

/** @internal */
export const UpdatePresetRequest$outboundSchema: z.ZodMiniType<
  UpdatePresetRequest$Outbound,
  UpdatePresetRequest
> = z.object({
  name: z.optional(z.string()),
  description: z.optional(z.nullable(z.string())),
  params: z.optional(z.record(z.string(), z.nullable(z.any()))),
});

export function updatePresetRequestToJSON(
  updatePresetRequest: UpdatePresetRequest,
): string {
  return JSON.stringify(
    UpdatePresetRequest$outboundSchema.parse(updatePresetRequest),
  );
}
