/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AvailableFormats,
  AvailableFormats$inboundSchema,
} from "./availableformats.js";
import { HateoasLinks, HateoasLinks$inboundSchema } from "./hateoaslinks.js";
import {
  ImageDimensions,
  ImageDimensions$inboundSchema,
} from "./imagedimensions.js";

export type UploadResponse = {
  /**
   * Image ID (first 16 characters of SHA256 hash)
   */
  id: string;
  /**
   * Full SHA256 hash of the image content
   */
  hash: string;
  /**
   * Primary CDN URL for the image
   */
  url: string;
  /**
   * All paths where this image is accessible
   */
  paths: Array<string>;
  /**
   * Whether this is a newly uploaded image (false if duplicate)
   */
  isNew?: boolean | undefined;
  /**
   * File size in bytes
   */
  size: number;
  /**
   * Detected image format
   */
  format: string;
  dimensions?: ImageDimensions | undefined;
  availableFormats: AvailableFormats;
  /**
   * Upload timestamp (RFC3339 format)
   */
  uploadedAt: Date;
  links: HateoasLinks;
};

/** @internal */
export const UploadResponse$inboundSchema: z.ZodMiniType<
  UploadResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    hash: types.string(),
    url: types.string(),
    paths: z.array(types.string()),
    is_new: types.optional(types.boolean()),
    size: types.number(),
    format: types.string(),
    dimensions: types.optional(ImageDimensions$inboundSchema),
    available_formats: AvailableFormats$inboundSchema,
    uploaded_at: types.date(),
    _links: HateoasLinks$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "is_new": "isNew",
      "available_formats": "availableFormats",
      "uploaded_at": "uploadedAt",
      "_links": "links",
    });
  }),
);

export function uploadResponseFromJSON(
  jsonString: string,
): SafeParseResult<UploadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadResponse' from JSON`,
  );
}
