/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { CurrentPeriod, CurrentPeriod$inboundSchema } from "./currentperiod.js";
import { PlanLimits, PlanLimits$inboundSchema } from "./planlimits.js";

/**
 * Current plan status
 */
export const PlanStatus = {
  Active: "active",
  Cancelling: "cancelling",
  Expired: "expired",
} as const;
/**
 * Current plan status
 */
export type PlanStatus = OpenEnum<typeof PlanStatus>;

export type UsageResponse = {
  /**
   * User's plan ID
   */
  plan: string;
  /**
   * Human-readable plan name
   */
  planName: string;
  /**
   * Current plan status
   */
  planStatus: PlanStatus;
  /**
   * Unix timestamp when subscription ends (for cancelling plans)
   */
  subscriptionEndsAt: number | null;
  planLimits: PlanLimits;
  /**
   * Total images (lifetime)
   */
  totalImages: number;
  /**
   * Total storage used in bytes
   */
  storageUsedBytes: number;
  /**
   * Total storage used in MB
   */
  storageUsedMb: number;
  /**
   * Total storage used in GB
   */
  storageUsedGb: number;
  currentPeriod: CurrentPeriod;
};

/** @internal */
export const PlanStatus$inboundSchema: z.ZodMiniType<PlanStatus, unknown> =
  openEnums.inboundSchema(PlanStatus);

/** @internal */
export const UsageResponse$inboundSchema: z.ZodMiniType<
  UsageResponse,
  unknown
> = z.pipe(
  z.object({
    plan: types.string(),
    plan_name: types.string(),
    plan_status: PlanStatus$inboundSchema,
    subscription_ends_at: types.nullable(types.number()),
    plan_limits: PlanLimits$inboundSchema,
    total_images: types.number(),
    storage_used_bytes: types.number(),
    storage_used_mb: types.number(),
    storage_used_gb: types.number(),
    current_period: CurrentPeriod$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "plan_name": "planName",
      "plan_status": "planStatus",
      "subscription_ends_at": "subscriptionEndsAt",
      "plan_limits": "planLimits",
      "total_images": "totalImages",
      "storage_used_bytes": "storageUsedBytes",
      "storage_used_mb": "storageUsedMb",
      "storage_used_gb": "storageUsedGb",
      "current_period": "currentPeriod",
    });
  }),
);

export function usageResponseFromJSON(
  jsonString: string,
): SafeParseResult<UsageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsageResponse' from JSON`,
  );
}
