/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UserSettings = {
  /**
   * Clerk user ID
   */
  id: string;
  /**
   * Username
   */
  username: string;
  /**
   * Email address
   */
  email?: string | undefined;
  /**
   * Preferred delivery formats (ordered)
   */
  deliveryFormats: Array<string>;
  /**
   * Default image quality (1-100)
   */
  defaultQuality: number;
  /**
   * Default fit mode
   */
  defaultFitMode: string;
  /**
   * Default maximum width
   */
  defaultMaxWidth?: number | undefined;
  /**
   * Default maximum height
   */
  defaultMaxHeight?: number | undefined;
  /**
   * UI theme
   */
  theme: string;
  /**
   * UI language
   */
  language: string;
  /**
   * Account creation timestamp (Unix epoch)
   */
  createdAt: number;
  /**
   * Last update timestamp (Unix epoch)
   */
  updatedAt: number;
  /**
   * Total number of uploads
   */
  totalUploads: number;
  /**
   * Total storage used in bytes
   */
  storageUsedBytes: number;
};

/** @internal */
export const UserSettings$inboundSchema: z.ZodMiniType<UserSettings, unknown> =
  z.pipe(
    z.object({
      id: types.string(),
      username: types.string(),
      email: types.optional(types.string()),
      delivery_formats: z.array(types.string()),
      default_quality: types.number(),
      default_fit_mode: types.string(),
      default_max_width: types.optional(types.number()),
      default_max_height: types.optional(types.number()),
      theme: types.string(),
      language: types.string(),
      created_at: types.number(),
      updated_at: types.number(),
      total_uploads: types.number(),
      storage_used_bytes: types.number(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "delivery_formats": "deliveryFormats",
        "default_quality": "defaultQuality",
        "default_fit_mode": "defaultFitMode",
        "default_max_width": "defaultMaxWidth",
        "default_max_height": "defaultMaxHeight",
        "created_at": "createdAt",
        "updated_at": "updatedAt",
        "total_uploads": "totalUploads",
        "storage_used_bytes": "storageUsedBytes",
      });
    }),
  );

export function userSettingsFromJSON(
  jsonString: string,
): SafeParseResult<UserSettings, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserSettings$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserSettings' from JSON`,
  );
}
