/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const Visibility = {
  Public: "public",
  Private: "private",
} as const;
export type Visibility = ClosedEnum<typeof Visibility>;

/** @internal */
export const Visibility$inboundSchema: z.ZodMiniEnum<typeof Visibility> = z
  .enum(Visibility);

/** @internal */
export const Visibility$outboundSchema: z.ZodMiniEnum<typeof Visibility> = z
  .enum(Visibility);
